Core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from .views import (
    HomeView,
    OrderSummaryView,
    ItemDetailView,
    Checkout_Page,
    add_to_cart,
    remove_from_cart,
    remove_Item_from_cart,
    add_item_to_cart,
    PayementView
)

urlpatterns = [
    path('', HomeView.as_view(), name='Home'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('checkout/',  Checkout_Page.as_view(), name=' Checkout_Page'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('remove_from_cart/<slug>',remove_from_cart, name='remove_from_cart'),
    path('remove_Item_from_cart/<slug>',remove_Item_from_cart, name='remove_Item_from_cart'),
    path('add_item_to_cart/<slug>',add_item_to_cart, name='add_item_to_cart'),
    path('payment/<payement-option>/', PayementView.as_view(), name='Payemnt')
]

EcommerceWebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include(('Core.urls','core'), namespace='core')),
]

Core/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import reverse
from django_countries.fields import CountryField

# Define category tuple and label tuple 
CATEGORY_CHOICES= (
    ('S','Shirt'),
    ('SW','Sport Wear'),
    ('OW','OutWear')
)

LABEL_CHOICES= (
    ('D','danger'),
    ('P','primary'),
    ('s','secondary')
)

# Create your models here.

class Item(models.Model):
    title= models.CharField(max_length=100)
    price= models.FloatField()
    discount_price=models.FloatField(null=True)
    category= models.CharField(choices=CATEGORY_CHOICES, max_length=3)
    label=models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug= models.SlugField()
    description=models.TextField()
    
    def __str__(self):
        return self.title 

    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            'slug':self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            'slug':self.slug
        })

    def remove_from_cart_url(self):
        return reverse("core:remove_from_cart", kwargs={
            'slug':self.slug
        })


class OrderItem(models.Model):
    user=models.ForeignKey(settings.AUTH_USER_MODEL,
                            on_delete=models.CASCADE, blank=True, null=True)
    item= models.ForeignKey(Item, on_delete=models.CASCADE)
    Ordered= models.BooleanField(default=False)
    quantity = models.IntegerField(default=2)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_Total_itemPrice(self):
        return self.quantity * self.item.price
        
    def get_TotalDiscounted_itemPrice(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_Total_itemPrice() - self.get_TotalDiscounted_itemPrice()
    
    def get_final_price(self):
        if self.item.discount_price:
            return self.get_TotalDiscounted_itemPrice()
        else:
            return self.get_Total_itemPrice()

class Order(models.Model):
    user=models.ForeignKey(settings.AUTH_USER_MODEL,
                            on_delete=models.CASCADE)
    items= models.ManyToManyField(OrderItem)
    start_date= models.DateTimeField(auto_now_add=True)
    ordered_date= models.DateTimeField()
    Ordered= models.BooleanField(default=False)
    billing_address=models.ForeignKey('Billingaddress', on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.user.username

    def get_Total_order_price(self):
        total=0
        for itemorder in self.items.all():
            total += itemorder.get_final_price()
        return total

class Billingaddress(models.Model):
    user=models.ForeignKey(settings.AUTH_USER_MODEL,
                            on_delete=models.CASCADE)
    street_address=models.CharField(max_length=100)
    apartment_address=models.CharField(max_length=100)
    country=CountryField(multiple=False)
    Zip=models.CharField(max_length=100)
    
    def __str__(self):
        return self.user.username

Core/forms.py
from django import forms
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget
PAYMENT_OPT=(
    ('S','Stripe'),
    ('P','Paypal')
)

class CheckoutForm(forms.Form):
    street_address= forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': '12543 Main st'
    }))
    apartment_address=forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Apartment or suite'
    }), required=False)
    country=CountryField(blank_label=('select country')).formfield(
        widget=CountrySelectWidget(attrs={
        'class': 'custom-select d-block w-100'
    }))
    Zip=forms.CharField(widget=forms.TextInput(attrs={
        'class':'form-control'
    }))
    same_billing_address= forms.BooleanField(widget=forms.CheckboxInput(), required=False)
    save_info = forms.BooleanField(widget=forms.CheckboxInput(), required=False)
    payment_options= forms.ChoiceField(widget=forms.RadioSelect(), choices=PAYMENT_OPT) 

Core/views.py
from django.shortcuts import render,get_object_or_404, redirect
from django.core.exceptions import ObjectDoesNotExist #used for checking if object is null or not
from django.contrib.auth.decorators import login_required #Cannot be used with class based views
from django.contrib.auth.mixins import LoginRequiredMixin #Used for Class based views 
from django.views.generic import ListView, DetailView, View
from .models import Item, OrderItem, Order, Billingaddress
from .forms import CheckoutForm
from django.utils import timezone
from django.contrib import messages 
# Create your views here.

class HomeView(ListView):
    model=Item 
    paginate_by= 12 
    template_name="home-page.html" 

class OrderSummaryView(LoginRequiredMixin, View):
   def get(self, *args, **kwargs):
       try:
           order=Order.objects.get(user=self.request.user, Ordered=False)
           context={
               'object': order
           }
           return render(self.request, 'order_summary.html', context)
       except ObjectDoesNotExist:
            message.error(self.request, "You do not have any active order at the moment!")
            return redirect('/')       

class ItemDetailView(DetailView):
    model=Item
    template_name ="product.html" 


class Checkout_Page(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):
        forms= CheckoutForm()
        context={
            'form': forms
        }
        return render(self.request,"checkout-page.html", context)

    def post(self, *args, **kwargs):
        forms= CheckoutForm(self.request.POST or None) 
        try:
            order= Order.objects.get(user=self.request.user, Ordered=False)
            if forms.is_valid():
                print(forms.cleaned_data)
                street_address=forms.cleaned_data('street_address')
                apartment_address=forms.cleaned_data('apartment_address')
                country=forms.cleaned_data('country')
                Zip=forms.cleaned_data('Zip')
                same_billing_address=forms.cleaned_data('same_billing_address')
                save_info=forms.cleaned_data('save_info')
                payment_options=forms.cleaned_data('payment_options')
                bilinaddress=Billingaddress(
                    user=self.request.user,
                    street_address=street_address,
                    apartment_address=apartment_address,
                    country=country,
                    Zip=Zip
                )
                bilinaddress.save()
                Order.billing_address=bilinaddress
                Order.save()

                message.info(self.request, "The form is valid")
                return redirect('core:checkout')
            message.warning(self.request, "The form is not valid")
            return redirect('/')
        except ObjectDoesNotExist:
            message.error(self.request, "You do not have any active order at the moment!")
            return redirect('core:/')

class PayementView(View):
    def get(self,*args,**kwargs):
        return render(self.request, "payment.html")


@login_required
def add_to_cart(request,slug):
    item=get_object_or_404(Item, slug=slug)
    Order_Item, created=OrderItem.objects.get_or_create(
        item=item,
        user=request.user,
        Ordered=False
        )
    order_qs= Order.objects.filter(user=request.user, Ordered=False)
    if order_qs.exists():
        order=order_qs[0]
        # check if order already exits add the quantity up
        if order.items.filter(item__slug=item.slug).exists():
            Order_Item.quantity +=1
            Order_Item.save()
            messages.info(request, "Your order has been updated! Thank you for shopping")
        else:
            order.items.add(Order_Item)
    else:
        ordered_date = timezone.now()
        order= Order.objects.create(user=request.user, ordered_date=ordered_date)
        order.items.add(Order_Item)
        messages.info(request, "Your order has been added to the cart! Thank you for shopping")
    return redirect("core:product", slug=slug)

@login_required
def remove_from_cart(request, slug):
    item=get_object_or_404(Item, slug=slug)
    order_qs= Order.objects.filter(user=request.user, Ordered=False)
    if order_qs.exists():
        order=order_qs[0]
        # check if order already exits add the quantity up
        if order.items.filter(item__slug=item.slug).exists():
            Order_Item=OrderItem.objects.filter(
                item=item,
                user=request.user,
                Ordered=False
            )[0]
            order.items.remove(Order_Item)
            messages.info(request, "Your order has been removed to the cart!")
        else:
            messages.info(request, "You have no order at the moment!")
            return redirect("core:product", slug=slug)
    else:
        messages.info(request, "You have no active order at the moment!")
        return redirect("core:product", slug=slug)
    return redirect("core:product", slug=slug)


@login_required
def remove_Item_from_cart(request, slug):
    item=get_object_or_404(Item, slug=slug)
    order_qs= Order.objects.filter(user=request.user, Ordered=False)
    if order_qs.exists():
        order=order_qs[0]
        # check if order already exits add the quantity up
        if order.items.filter(item__slug=item.slug).exists():
            Order_Item=OrderItem.objects.filter(
                item=item,
                user=request.user,
                Ordered=False
            )[0]
            if Order_Item.quantity >1:
                Order_Item.quantity -=1
                Order_Item.save()
                messages.info(request, "Your order has been updated!")
                return redirect("core:order-summary")
            else:
                order.items.remove(Order_Item)
                messages.info(request, "You have no order at the moment!")
                return redirect("core:Home")
       
    else:
        messages.info(request, "You have no active order at the moment!")
        return redirect("core:product", slug=slug)
    return redirect("core:product", slug=slug)


@login_required
def add_item_to_cart(request,slug):
    item=get_object_or_404(Item, slug=slug)
    Order_Item, created=OrderItem.objects.get_or_create(
        item=item,
        user=request.user,
        Ordered=False
        )
    order_qs= Order.objects.filter(user=request.user, Ordered=False)
    if order_qs.exists():
        order=order_qs[0]
        # check if order already exits add the quantity up
        if order.items.filter(item__slug=item.slug).exists():
            Order_Item.quantity +=1
            Order_Item.save()
            messages.info(request, "Your order has been updated!")
            return redirect("core:order-summary")
        else:
            messages.info(request, "You have no order at the moment!")
            return redirect("core:product")
    else:
        ordered_date = timezone.now()
        order= Order.objects.create(user=request.user, ordered_date=ordered_date)
        order.items.add(Order_Item)
        messages.info(request, "Your order has been added to the cart! Thank you for shopping")
    return redirect("core:product", slug=slug)

Core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>
    {% block head_title %}
    {% endblock %}
  </title>
  {% block extra_head %}
  {% endblock %}
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>
</head>

{% include "navbar.html" %}

<body>
    <!--Message in base html using Django-->
    <div class="mt-5 pt-4 pr-4">
      {% if messages %}
        <ul class="messages">
          {% for message in messages %}
           <div class="alert alert-{{ message.tags }}" role="alert">
             {{ message }}
           </div>
          {% endfor %}
        </ul>
      {% endif %}
    </div>  

    {% block content %}
    {% endblock content %}

    {% block extra_body %}
    {% endblock extra_body %}

    {% include "footer.html" %}
    {% include "script.html" %}
    
    {% block extra_scripts %}
    {% endblock extra_scripts %}
</body>

Core/templates/checkout-page.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
  <!--Main layout-->
  <main class="mt-3 pt-3">
    <div class="container wow fadeInDownBig">

      <!-- Heading -->
      <h2 class="my-5 h2 text-center">Checkout form</h2>

      <!--Grid row-->
      <div class="row">

        <!--Grid column-->
        <div class="col-md-8 mb-4">

          <!--Card-->
          <div class="card">
            <!--Card content-->
            <form class="card-body">
              <!--address-->
              <div class="md-form mb-5">
                <label for="zip">Address</label>
                {{form.street_address}}
              </div>

              <!--address-2-->
              <div class="md-form mb-5">
                <label for="zip">Apartment Address</label>
                {{form.apartment_address}}
              </div>

              <!--Grid row-->
              <div class="row">

                <!--Grid column-->
                <div class="col-lg-4 col-md-12 mb-4">
                  <label for="zip">Country</label>
                  {{form.country}}
                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-lg-4 col-md-6 mb-4">
                  <label for="zip">Zip</label>
                  {{form.Zip}}
                </div>
                <!--Grid column-->

              </div>
              <!--Grid row-->

              <hr>

              <div class="custom-control custom-checkbox">
                {{form.same_billing_address}}
                <label for="same-address">Shipping address is the same as my billing address</label>
              </div>
              <div class="custom-control custom-checkbox">
                {{form.save_info}}
                <label for="save-info">Save this information for next time</label>
              </div>

              <hr>

              <div class="d-block my-3">
                <label for="zip">Payment Method</label>
                  {% for value, name in form.fields.payment_options.choices %}
                  <div class="custom-control custom-radio">
                  <input id='{{name}}' name="payment_option" value='{{value}}' type="radio" class="custom-control-input" checked required>
                  <label class="custom-control-label" for='{{name}}'>{{name}}</label>
                  </div>
                  {%endfor%}
                
              </div>
              
              <hr class="mb-4">
              <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>

            </form>

          </div>
          <!--/.Card-->

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-4 mb-4">

          <!-- Heading -->
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Your cart</span>
            <span class="badge badge-secondary badge-pill">3</span>
          </h4>

          <!-- Cart -->
          <ul class="list-group mb-3 z-depth-1">
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">Product name</h6>
                <small class="text-muted">Brief description</small>
              </div>
              <span class="text-muted">$12</span>
            </li>
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">Second product</h6>
                <small class="text-muted">Brief description</small>
              </div>
              <span class="text-muted">$8</span>
            </li>
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">Third item</h6>
                <small class="text-muted">Brief description</small>
              </div>
              <span class="text-muted">$5</span>
            </li>
            <li class="list-group-item d-flex justify-content-between bg-light">
              <div class="text-success">
                <h6 class="my-0">Promo code</h6>
                <small>EXAMPLECODE</small>
              </div>
              <span class="text-success">-$5</span>
            </li>
            <li class="list-group-item d-flex justify-content-between">
              <span>Total (USD)</span>
              <strong>$20</strong>
            </li>
          </ul>
          <!-- Cart -->

          <!-- Promo code -->
          <form class="card p-2">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Promo code" aria-label="Recipient's username" aria-describedby="basic-addon2">
              <div class="input-group-append">
                <button class="btn btn-secondary btn-md waves-effect m-0" type="button">Redeem</button>
              </div>
            </div>
          </form>
          <!-- Promo code -->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->

{% endblock content %}
  
  

Core/templates/footer.html
  <!--Footer-->
  <footer class="page-footer text-center font-small mt-4 wow fadeIn ">

    <!-- Social icons -->
    <div class="pb-2 mt-2 pt-3 " style="background-color:#181818">
      <a href="https://www.facebook.com/mdbootstrap" target="_blank">
        <i class="fab fa-facebook-square fa-2x"></i>
      </a>
      <a href="https://www.facebook.com/mdbootstrap" target="_blank">
        <i class="fab fa-facebook-square  ml-3 fa-2x"></i>
      </a>
      <a href="https://www.facebook.com/mdbootstrap" target="_blank">
        <i class="fab fa-facebook-square ml-3 fa-2x"></i>
      </a>
    </div>
   
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3" style="background-color:#020202">
      © 2019 Copyright:
      <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> MDBootstrap.com </a>
    </div>
    <!--/.Copyright-->

  </footer>
  <!--/.Footer-->

Core/templates/home-page.html
{% extends "base.html" %}

{% block content %}

  <!--Main layout-->
  <main>
    <div class="container">

      <!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark mt-3 mb-5 wow fadeInDownBig "  style="background-color:#1f1f1f">

        <!-- Navbar brand -->
        <span class="navbar-brand">Categories:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">All
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Shirts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Sport wears</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Outwears</a>
            </li>

          </ul>
          <!-- Links -->

          <form class="form-inline">
            <div class="md-form my-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            </div>
          </form>
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->

      <!--Section: Products v.3-->
      <section class="text-center mb-4 wow fadeInUpBig">

        <!--Grid row-->
        <div class="row wow fadeIn">
          {% for item in object_list  %}

          <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-4">

            <!--Card-->
            <div  class="card">
              <!--Card image-->
              <div class="view overlay">
                <img  src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/15.jpg" class="card-img-top"
                  alt="">
                <a href="{{ item.get_absolute_url }}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <!--Card image-->

              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                <a href="{{ item.get_absolute_url }}" class="grey-text">
                  <h5>{{item.get_category_display}}</h5>
                </a>
                <h5>
                  <strong>
                    <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{item.title}}
                      <span class="badge badge-pill {{item.get_label_display}}-color">bestseller</span>
                    </a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                  <strong> $
                    {%if item.discount_price%}
                    {{item.discount_price}}
                    {%else%}
                    {{item.price}} 
                    {%endif%}
                  </strong>
                </h4>
              
              </div>
              <!--Card content-->            
            </div>
            <!--Card-->

          </div>
          <!--Grid column-->
          {% endfor %}
        </div>
        <!--Grid row-->

      </section>
      <!--Section: Products v.3-->

      <!--Pagination-->
      {%if is_paginated %}
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

          <!--Arrow left-->
          {%if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{page_obj.previous_page_number}}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {%endif%}

          <li class="page-item active">
            <a class="page-link" href="?page={{page_obj.number}}">{{page_obj.number}}
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <!-- <li class="page-item">
            <a class="page-link" href="#">2</a>
          </li> -->
         
          {%if page_obj.has_next%}
          <li class="page-item">
            <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {%endif%}
        </ul>
      </nav>
      {%endif%}
      <!--Pagination-->

    </div>
  </main>
  <!--Main layout-->
{% endblock content %}
  

Core/templates/order_summary.html
{% extends "base.html" %}

{% block content %}

  <!--Main layout-->
  <main>
    <div class="container pt-4 mt-4 mb-3 pb-4">
          <div class="table-responsive table-dark ">
                <table class="table text-light">
                    <h2 class="text-center bg-white text-dark pb-4 ">Order Summary</h2>
                        <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Item Title</th>
                            <th scope="col">Quantity</th>
                            <th scope="col">Unit Price</th>
                            <th scope="col">Total Price</th>
                        </tr>
                        </thead>
                        {%for Order_item in object.items.all%}
                        <tbody>
                        <tr class="font-weight-bold bg-warning text-dark ">
                            <th  scope="row ">{{forloop.counter}}</th>
                            <td>{{ Order_item.item.title}}</td>
                            <td>
                              <a href="{% url 'core:add_item_to_cart' Order_item.item.slug %}">
                              <i class="far fa-plus-square"></i></a>
                              {{ Order_item.quantity}}
                              <a href="{% url 'core:remove_Item_from_cart' Order_item.item.slug %}"><i class="far fa-minus-square"></i></a>
                            </td>                           
                            <td>{{ Order_item.item.price}}</td>
                            <td>
                                {%if Order_item.item.discount_price%}
                                  rs{{Order_item.get_TotalDiscounted_itemPrice}}
                                  <span class="badge badge-dark ml-2">Saving rs{{Order_item.get_amount_saved}}</span>
                                {%else%}
                                {{Order_item.get_Total_itemPrice}}
                                {%endif%}
                            </td>
                        </tr>
                        </tbody>
                        {%endfor%}
                        <tr>
                          <td colspan="4" class="ml-5 pl-5 text-center font-weight-bold">Order total </td>
                          <td class="font-weight-bold">
                            rs {{object.get_Total_order_price}}
                          </td>
                        </tr>
                </table>
          </div>
    </div>
    <div class="container col-6 pt-4 mt-4 mb-3 pb-4" >
      <a type="button" class="btn btn-lg btn-warning pull-right" href="/" >Continue Shopping</a>
      <a type="button" class="btn btn-dark btn-lg pull-right" href="/checkout/">Checkout</a>
    </div>
            
  </main>
  <!--Main layout-->
{% endblock content %}
  

Core/templates/product.html
{% extends "base.html" %}

{% block content %}
  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/14.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">{{object.get_category_display}}</span>
              </a>
            </div>

            <p class="lead">
                {%if object.discount_price%}
                <span class="mr-1">
                  <del>${{object.price}} </del>
                </span>
                {{object.discount_price}}
                {%else%}
                <span>$
                {{object.price}} 
                {%endif%}</span>
            </p>

            <p class="lead font-weight-bold">Description</p>

            <p>{{object.description}}</p>

            <!--<form class="d-flex justify-content-left">
              
           <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
            </form>
           !-->
            <a href="{{object.get_add_to_cart_url}}" class="btn btn-primary btn-md my-0 p" >Add to cart
              <i class="fas fa-shopping-cart ml-1"></i>
            </button>
            <a href="{{object.remove_from_cart_url}}" class="btn btn-danger btn-md my-0 p" >Remove from cart
            </a>
            </button>
          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 text-center">

          <h4 class="my-4 h4">Additional information</h4>

          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
            voluptates,
            quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-lg-4 col-md-12 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->

{% endblock content %}